import Header from '@/components/header/Header';
import '../styles/globals.css';
import { Akshar } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const akshar = Akshar({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={akshar.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
